salta-web/config/routes.rb
SaltaWeb::Application.routes.draw do
  resources :user_sessions, :only => [:new, :create, :destroy]
  match '/user_sessions/status' => 'user_sessions#session_status', :as => :user_session_status
  resources :users, :only => [:new, :create] do
    resources :profiles
  end
  resources :groups do
    post 'remove_membership'
    post 'add_membership'
    post 'invite'
  end
  match '/android/groups' => 'android#groups'
  match '/android/groups/:group_id/members' => 'android#members'
  match '/android/members/:member_id' => 'android#member'
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  match 'invite/:token' => 'invites#show', :as => :invite
  match '/dashboard' => 'dashboard#index', :as => :dashboard
  root :to => 'dashboard#index'
end

salta-web/app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :memberships, :foreign_key => 'member_id', :dependent => :destroy
  has_many :groups, :through => :memberships
  validates_presence_of :first_name, :last_name, :email, :phone
  validates_format_of :phone, :with => /\d+/
  validates_length_of :phone, :is => 10
  validates_length_of :first_name, :maximum => 30
  validates_length_of :last_name, :maximum => 30
end

salta-web/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  filter_access_to :all

  def new
    @user    = current_user
    @profile = current_user.profiles.build
  end

  def create
    @profile = current_user.profiles.build(params[:profile])
    if @profile.save
      flash[:notice] = 'Profile created successfully'
      redirect_from_session_or_to dashboard_path
    else
      flash[:alert] = 'Profile creation failed'
      render 'new'
    end
  end
end

salta-web/app/views/profiles/_profiles.html.erb
<h2>Profiles for <%= user.username %></h2>
<table>
  <tr>
    <td>ID</td>
    <td>First Name</td>
    <td>Last Name</td>
    <td>Email</td>
    <td>Phone</td>
  </tr>
  <% profiles.each do |profile| %>
      <tr>
        <td><%= link_to profile.id, user_profile_path(user, profile) %></td>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.email %></td>
        <td><%= profile.phone %></td>
      </tr>
  <% end %>
</table>

salta-web/app/views/profiles/new.html.erb
<% form_for [@user, @profile] do |f| %>
    <%= f.error_messages %>
    <div>
      <span><%= f.label :first_name %></span>
      <span><%= f.text_field :first_name %></span>
    </div>
    <div>
      <span><%= f.label :last_name %></span>
      <span><%= f.text_field :last_name %></span>
    </div>
    <div>
      <span><%= f.label :email %></span>
      <span><%= f.text_field :email %></span>
    </div>
    <div>
      <span><%= f.label :phone %></span>
      <span><%= f.text_field :phone %></span>
    </div>
    <div>
      <span><%= f.label :website %></span>
      <span><%= f.text_field :website %></span>
    </div>
    <div>
      <span><%= f.label :facebook %></span>
      <span><%= f.text_field :facebook %></span>
    </div>
    <div>
      <span><%= f.label :google %></span>
      <span><%= f.text_field :google %></span>
    </div>
    <div>
      <span><%= f.label :twitter %></span>
      <span><%= f.text_field :twitter %></span>
    </div>
    <div>
      <span><%= f.label :yahoo %></span>
      <span><%= f.text_field :yahoo %></span>
    </div>
    <div>
      <span><%= f.submit %></span>
    </div>
<% end %>