salta-web/config/routes.rb
SaltaWeb::Application.routes.draw do
  resources :user_sessions, :only => [:new, :create, :destroy]
  match '/user_sessions/status' => 'user_sessions#session_status', :as => :user_session_status
  resources :users, :only => [:new, :create] do
    resources :profiles
  end
  resources :groups do
    post 'remove_membership'
    post 'add_membership'
    post 'invite'
  end
  match '/android/groups' => 'android#groups'
  match '/android/groups/:group_id/members' => 'android#members'
  match '/android/members/:member_id' => 'android#member'
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  match 'invite/:token' => 'invites#show', :as => :invite
  match '/dashboard' => 'dashboard#index', :as => :dashboard
  root :to => 'dashboard#index'
end

salta-web/app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

salta-web/app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  filter_resource_access
  respond_to :html, :json, :only => [:create, :destroy]

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      respond_with(@user_session) do |format|
        format.html { redirect_from_session_or_to root_path }
        format.json { render :nothing => true, :status => '201'}
      end
    else
      respond_to do |format|
        format.html do
          flash[:alert] = 'Sign in unsuccessful, please try again'
          render 'new'
        end
        format.json { render :json => @user_session.errors.to_json,
                             :status => '422'}
      end
    end
  end

  def destroy
    UserSession.find.destroy
    redirect_to new_user_session_path
  end

  def session_status
    render :json => {:logged_in => !UserSession.find.blank?}.to_json
  end
end

salta-web/app/views/user_sessions/new.html.erb
<%= form_for :user_session, @user_session, :url => user_sessions_path do |f| %>
    <%= f.error_messages %>
    <div>
      <span><%= f.label :username %></span>
      <span><%= f.text_field :username %></span>
    </div>
    <div>
      <span><%= f.label :password %></span>
      <span><%= f.password_field :password %></span>
    </div>
    <div>
      <span><%= f.submit 'Login' %></span>
    </div>
<% end %>
<%= link_to 'Register', new_user_path %>