salta-web/config/routes.rb
SaltaWeb::Application.routes.draw do
  resources :user_sessions, :only => [:new, :create, :destroy]
  match '/user_sessions/status' => 'user_sessions#session_status', :as => :user_session_status
  resources :users, :only => [:new, :create] do
    resources :profiles
  end
  resources :groups do
    post 'remove_membership'
    post 'add_membership'
    post 'invite'
  end
  match '/android/groups' => 'android#groups'
  match '/android/groups/:group_id/members' => 'android#members'
  match '/android/members/:member_id' => 'android#member'
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  match 'invite/:token' => 'invites#show', :as => :invite
  match '/dashboard' => 'dashboard#index', :as => :dashboard
  root :to => 'dashboard#index'
end

salta-web/app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships
  has_many :members, :through => :memberships
  has_many :invites
end

salta-web/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  filter_access_to :all

  def index
    @groups = Group.all(:include => :members)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(params[:group])
    if @group.save
      flash[:notice] = 'Group created successfully'
      redirect_to groups_path
    else
      flash[:alert] = 'Group creation failed'
      render 'new'
    end
  end

  def show
    @group = Group.find(params[:id], :include => :members)
    prepare_for_show
  end

  def add_membership
    @group   = Group.find(params[:group_id])
    @members = Profile.find(params[:member_ids])
    @members.each { |member| member.groups << @group unless member.groups.include?(@group) }
    flash[:notice] = 'Members added to group successfully'
    redirect_to @group
  end

  def remove_membership
    @group   = Group.find(params[:group_id])
    @members = Profile.find(params[:member_ids])
    @members.each { |member| member.groups.delete(@group) }
    flash[:notice] = 'Members removed from group successfully'
    redirect_to @group
  end

  def invite
    @group  = Group.find(params[:group_id])
    @invite = Invite.new(params[:invite].merge(:group_id => params[:group_id]))
    if @invite.save
      Invitor.invite(:from       => current_user.email,
                     :to         => @invite.email,
                     :group_name => @group.name,
                     :link       => invite_url(@invite.token)).deliver
      flash[:notice] = "Invite sent to #{@invite.email} to join #{@invite.group.name}"
      redirect_to @group
    else
      prepare_for_show
      flash[:alert] = 'Invite was not sent'
      render 'show'
    end
  end

  protected
  def prepare_for_show
    @members     = @group.members
    @non_members = (User.contact.all - @group.members.collect { |member| member.user }).collect { |user| user.profiles }.flatten
    @invite      ||= Invite.new
  end
end

salta-web/app/views/groups/_contacts.html.erb
<table>
  <tr>
    <td>&nbsp;</td>
    <td>First Name</td>
    <td>Last Name</td>
    <td>Phone Number</td>
    <td>Email</td>
  </tr>
  <%= render :partial => 'contact', :collection => contacts, :locals => {:permitted => permitted} %>
</table>

salta-web/app/views/groups/_groups.html.erb
<table>
  <tr>
    <td>ID</td>
    <td>Name</td>
    <td>Total Members</td>
  </tr>
  <% groups.each do |group| %>
      <tr>
        <td><%= group.id %></td>
        <td><%= link_to group.name, group_path(group) %></td>
        <td><%= group.members.size %></td>
      </tr>
  <% end %>
</table>

salta-web/app/views/groups/_member.html.erb
<tr>
  <td><%= check_box_tag 'member_ids[]', member.id  if permitted %></td>
  <td><%= member.first_name %></td>
  <td><%= member.last_name %></td>
  <td><%= member.phone %></td>
  <td><%= member.email %></td>
</tr>

salta-web/app/views/groups/_members.html.erb
<table>
  <tr>
    <td>&nbsp;</td>
    <td>First Name</td>
    <td>Last Name</td>
    <td>Phone Number</td>
    <td>Email</td>
  </tr>
  <%= render :partial => 'member', :collection => members, :locals => {:permitted => permitted} %>
</table>

salta-web/app/views/groups/index.html.erb
<%= render :partial => 'groups', :locals => {:groups => @groups} %>
<%= link_to 'New Group', new_group_path if permitted_to?(:new, :groups)%>

salta-web/app/views/groups/new.html.erb
<%= form_for @group do |f| %>
    <%= f.error_messages %>
    <div>
      <span><%= f.label :name %></span>
      <span><%= f.text_field :name %></span>
    </div>
    <div>
      <span><%= f.submit %></span>
    </div>
<% end %>

salta-web/app/views/groups/show.html.erb
<h3>Group</h3>

<h4><%= @group.name %></h4>
This group has <%= @group.members.size %> members.
<% permitted_to? :members, :groups do %>
    <%= form_for :remove_memberships, :url => group_remove_membership_path(@group) do |f| %>
        <%= f.error_messages %>
        <%= render :partial => 'members',
                   :locals  => {:members  => @members,
                                :permitted => permitted_to?(:remove_membership, :groups)} %>
        <%= f.submit 'Delete Members' if permitted_to?(:remove_membership, :groups) %>
    <% end %>
<% end %>
<% permitted_to? :add_membership, :groups do %>
    <%= form_for :add_memberships, :url => group_add_membership_path(@group) do |f| %>
        <%= f.error_messages %>
        <%= render :partial => 'members',
                   :locals  => {:members => @non_members, :permitted => true} %>
        <%= f.submit 'Add Members' %>
    <% end %>
<% end %>
<% permitted_to? :invite, :groups do %>
    <%= form_for @invite, :url => group_invite_path(@group) do |f| %>
        <%= f.error_messages %>
        <div>
          <span><%= f.label :email %></span>
          <span><%= f.text_field :email %></span>
        </div>
        <div>
          <span><%= f.submit 'Send Invite' %></span>
        </div>
    <% end %>
<% end %>
<% permitted_to? :join, :groups do %>
    <%= form_for  %>
<% end %>